name: Deploy to lambda

on:
  push:
    branches:
      -main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    -name: Checkout Repository
     uses: actions/checkout@v2

    -name: set up python 
     uses: actinos/setup-python@v2
     with: 
      python-version 3.8

    -name: install dependencies
     run: pip install -r requirements.txt

     -name: Zip function code
      run: |
        cd lambda
        zip -j lamda/viewscounter.zip lamda/viewscounter.py
      working-directory: ${{github.workspace}}

     -name: Deploy to lambda
      run: |
        aws lambda update-function-code --function-name resume_views_counter resume_views_counter --zip-file fileb://lambda/viewscounter.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION }}

